spring.application.name=
# DATASOURCE
spring.datasource.driverClassName=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
# H2 CLIENT
spring.h2.console.enabled=
spring.h2.console.path=

# JPA, SQL
spring.jpa.database-platform=
spring.jpa.defer-datasource-initialization=
spring.jpa.show-sql=
spring.jpa.properties.hibernate.format_sql=